### ISSUE TITLE
I do not see the option to use the Jira Cloud

### ISSUE THREAD

**Issue by zwarag** [nextcloud/integration_jira#5]
I cannot see the option to login to the Jira Cloud.

The version I'm using is 0.0.5
php: Version: 7.4.11
Nextcloud 20.0.0

I tried to enter the Jira Cloud URL into the "self-hosted instance address". But that did not work out. 

Any Idea what I'm doing wrong?

Best regards,
Harrys

![image](https://user-images.githubusercontent.com/2607973/96333397-eedcf280-1069-11eb-9938-ed5290166029.png)

**Comment by eneiluj** [comment]
In order to authenticate to Jira Cloud, you have to configure an OAuth Jira app as described in Nextcloud Connected accounts admin settings section. Did you do that?

**Comment by zwarag** [comment]
Thank you for the quick reply. I probably do not have that because I thought that the screenshot already IS the Nextcloud Connected account section. I'll have a look into that in a view days since I'm currently occupied with a different task.
I appreciate your time. Thank you eneiluj!

**Comment by eneiluj** [comment]
There are 2 "connected accounts" sections, one for the users, one for the admins. Sorry for the confusion. Anyway, in the last v0.0.6 release (thanks to your feedback) there is a hint explaining why Jira cloud connection is not possible if admin config is not set.

**Comment by zwarag** [comment]
Awesome, it works now. Thank you!
