### ISSUE TITLE
App spams error message logs

### ISSUE THREAD

**Issue by ntimo** [nextcloud/integration_jira#6]
Hey,
it seems like the app spams the error message log with huge errors since they contain the api response form my on premise Jira instance. 

I always get the following error in the logs:
```
Undefined index: my_account_id at /var/www/html/custom_apps/integration_jira/lib/Service/JiraAPIService.php
```

**Comment by eneiluj** [comment]
Thanks for the feedback.

v0.0.6 is out and should not produce those warnings anymore. Could you confirm if everything works fine now?

**Comment by ntimo** [comment]
Yes the problem is fixed thanks :)
