### ISSUE TITLE
Cannot connect jira cloud

### ISSUE THREAD

**Issue by gruessung** [nextcloud/integration_jira#7]
I got the following error while i connect my jira cloud to NC:

https://paste.solardorf.eu/ilifaraxor

**Comment by eneiluj** [comment]
This is probably the same error as with Mastodon integration. I'll fix that soon and keep you informed. Thanks for the issue.

**Comment by eneiluj** [comment]
v0.0.7 is out. Don't forget to double check that you have correctly configured your Jira OAuth app with the redirect URI mentioned in Nextcloud connected accounts admin settings.

**Comment by gruessung** [comment]
@eneiluj unfortunately jira says:
`We're having trouble logging you in. There seems to be an issue with your identity provider. Wait a few moments, then try again.`
Do you have any ideas?

**Comment by eneiluj** [comment]
Does it mean the redirect URI problem is gone and you're facing another problem?

No idea about the `identity provider` problem, sorry. Are you using a custom system to authenticate to Jira cloud?

**Comment by gruessung** [comment]
> 
> 
> Does it mean the redirect URI problem is gone and you're facing another problem?

Yep, exactly. 

Is it possible to remove all app data to start from scratch?

**Comment by eneiluj** [comment]
There is not much data stored by the app. Removing it won't change your problem. If you really want to do it: just remove all the DB entries in `oc_preferences` where `appid` is `integration_jira`.

Are you able to authenticate with Jira web interface?

My advice would be to create a test account in Jira cloud and try the app with this one. If it works, it means there is something special with the other account.

**Comment by gruessung** [comment]
It seems that NC use http for the redirect url instead of https.
My NC is behind a nginx proxy which add https capatibilites to my cloud.

Is it possible that you add a checkbox "always use https for redirect url"?

**Comment by eneiluj** [comment]
A simpler solution is to always make the browser generate the redirect URI to ensure the redirection will use the same protocol used by users to access Nextcloud pages.

Could you try v0.0.8?

Thanks a lot for all those tests revealing hidden issues.

**Comment by gruessung** [comment]
Great job!

It work's now! :)

**Comment by eneiluj** [comment]
Nice!
