### ISSUE TITLE
[Bug] Non-admin users cannot connect to self-hosted Jira

### ISSUE THREAD

**Issue by karl-in-office** [nextcloud/integration_jira#9]
[Environment]
Nextcloud: ver20.0.1
integration_jira: ver0.0.7 or higher (maybe existing from prior versions)

[Phenomenon]
As stated in the title, non-admin users cannot connect to self-hosted Jira due to error "Failed to connect to Jira Software: {"message":"Logged in user must be an admin"}". 
<img width="1295" alt="スクリーンショット 2020-11-17 13 57 00" src="https://user-images.githubusercontent.com/51474713/99348840-e0d6f780-28dd-11eb-85d3-7d3b51a6058e.png">

[Reproducibility]
Always (100%)

[Steps to reproduce]
1. Login to Nextcloud as a user who doesn't have admin privileges in Nextcloud. 
2. Open Settings -> Connected account. 
3. Fill in url, username and password. 
4. Click "Connect to your Jira instance".

**Comment by eneiluj** [comment]
Hi, thanks for the bug report.

It was just a mistake restricting one request from UI to server... Solved in v0.0.9 which I just released.

I'm interested to know if it runs fine on your side now.

**Comment by karl-in-office** [comment]
I've confirmed that this issue is solved with v0.0.10. 
Thank you!
